import { Row } from './row';
import { Letter } from './letter';

export let puzzle = [
    new Row(new Array(new Letter(null), new Letter('1'), new Letter('2'),
        new Letter('3'), new Letter('4'), new Letter('5'), new Letter('6'),
        new Letter('7'), new Letter('8'), new Letter('9'), new Letter('10'),
        new Letter('11'), new Letter('12'), new Letter('13'), new Letter('14'), new Letter('15'))),
    new Row(new Array(new Letter('A'), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null), new Letter(null))),
    new Row(new Array(new Letter('B'), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null), new Letter(null))),
    new Row(new Array(new Letter('C'), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null), new Letter(null))),
    new Row(new Array(new Letter('D'), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null), new Letter(null))),
    new Row(new Array(new Letter('E'), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null), new Letter(null))),
    new Row(new Array(new Letter('F'), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null), new Letter(null))),
    new Row(new Array(new Letter('G'), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null), new Letter(null))),
    new Row(new Array(new Letter('H'), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null), new Letter(null))),
    new Row(new Array(new Letter('I'), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null), new Letter(null))),
    new Row(new Array(new Letter('J'), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null), new Letter(null))),
    new Row(new Array(new Letter('K'), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null), new Letter(null))),
    new Row(new Array(new Letter('L'), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null), new Letter(null))),
    new Row(new Array(new Letter('M'), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null), new Letter(null))),
    new Row(new Array(new Letter('N'), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null), new Letter(null))),
    new Row(new Array(new Letter('O'), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null),
        new Letter(null), new Letter(null), new Letter(null), new Letter(null), new Letter(null)))
];

export class Scrabble{
    placeLetter(letter : string, row: number, col: number ){
        puzzle[row].letters[col] = new Letter(letter);
    }
}
